export const Colors = {
  light: {
    primary: "#ED225D",
    onPrimary: "#FFFFFF",
    primaryContainer: "#FF4F75",
    onPrimaryContainer: "#5A001C",
    primaryFixedDim: "#FFB2BB",
    p5Pink: "#ED225D",
    p5Dark: "#222222",
    p5Light: "#F5F5F5",
    surface: "#FFFFFF",
    onSurface: "#000000",
    surfaceDim: "#F3F4F6",
    surfaceBright: "#FFFFFF",
    surfaceContainer: "#F5F5F5",
    surfaceContainerLow: "#FAFAFA",
    surfaceContainerHigh: "#EFEFEF",
    surfaceContainerHighest: "#E5E5E5",
    surfaceContainerLowest: "#FFFFFF",
    onSurfaceVariant: "#49454F",
    outline: "#000000",
    outlineVariant: "#C4C4C4",
    textSecondary: "#6B7280",
    inverseSurface: "#000000",
    inverseOnSurface: "#FFFFFF",
    error: "#BA1A1A",
    errorContainer: "#FFDAD6",
    onError: "#FFFFFF",
    onErrorContainer: "#410002",
  },
  dark: {
    primary: "#ED225D",
    onPrimary: "#FFFFFF",
    primaryContainer: "#FF4F75",
    onPrimaryContainer: "#5A001C",
    primaryFixedDim: "#FFB2BB",
    p5Pink: "#ED225D",
    p5Dark: "#222222",
    p5Light: "#F5F5F5",
    surface: "#121317",
    onSurface: "#E3E2E7",
    surfaceDim: "#121317",
    surfaceBright: "#38393D",
    surfaceContainer: "#1E1F23",
    surfaceContainerLow: "#1A1B1F",
    surfaceContainerHigh: "#292A2E",
    surfaceContainerHighest: "#343539",
    surfaceContainerLowest: "#0D0E12",
    onSurfaceVariant: "#E4BDC0",
    outline: "#AB888B",
    outlineVariant: "#5C3F42",
    textSecondary: "#9CA3AF",
    inverseSurface: "#E3E2E7",
    inverseOnSurface: "#2F3034",
    error: "#FFB4AB",
    errorContainer: "#93000A",
    onError: "#690005",
    onErrorContainer: "#FFDAD6",
  },
} as const;

export type ThemeColorScheme = keyof typeof Colors;
export type ThemeColorKey = keyof typeof Colors.light;
