name: Build & Publish Release APK

on:
  push:
    tags:
      - "*"

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build app
        run: chmod +x ./gradlew &&
          ./gradlew assembleRelease
      - name: Release
        uses: sangatdesai/release-apk@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_FOLDER: app
